config/routes.rb
FullcalendarMasterRails3::Application.routes.draw do

  resources :attachments do
    get "serve", :on => :member
  end

  get "download_file" => "attachments#download_file", as: 'download_file'

  resources :information

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]

  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' 
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/roadmap', to: 'static_pages#roadmap'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'events#index'

  post  'events/demo_create' => 'events#demo_create'

  get   'events/db_cleanup'    => 'events#db_cleanup', :as => 'db_cleanup'
  get   'events/get_events' => 'events#get_events', :as => 'get_events'
  post  'events/resize'     => 'events#resize'
  post  'events/move'       => 'events#move'

  resources :events

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @flag = 'home'
    render 'events/index'
  end

  def help
    @flag = 'help'
    render_site_info
  end

  def about
    @flag = 'about'
    render_site_info
  end

  def contact
    @flag = 'contact'
    render_site_info
  end

  def roadmap
    @flag = 'roadmap'
    render_site_info
  end

    private
    def render_site_info
      render 'static_pages/site_info'
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_about.html.erb
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">このサイトは･･･</a></li>
		<li><a href="#tabs-2">開発環境</a></li>
		<li><a href="#tabs-3">ソースコード･･･etc</a></li>
	</ul>
  <div id="tabs-1">
    <dl id = "about_site_info" >

      <dt>
        このサイトは管理人が趣味と学習を兼ねて運営しているサイトです。
        
      </dt>
      <dd>
        つまり、料金が派生する商用サイトではありません。<br/>
        また、今後も課金の予定はありません。
      </dd>

      <dt>
        免責事項
      </dt>
      <dd style = "display: none;">
        このサイトご利用の際は自己責任でお願いします。
        本サイトに掲載する情報には充分に注意を払っていますが、その内容について保証するものではありません。
        管理人は本ウェブサイトの使用ならびに閲覧によって生じたいかなる損害にも責任を負いかねます。
        本サイトのURLや情報は予告なく変更される場合があります。
      </dd>

      <dt>
        個人情報について
      </dt>
      <dd style = "display: none;">
        本サイトでは、皆さんがユーザー登録した時の名前、e-mailアドレス等の
        個人情報は皆さんの当サイトアクセスの目的以外では使用しません。
        また本サイトでは、皆さんの情報やプライバシーをお守りするために、
        SSLによる暗号化通信を行っています。
      </dd>

    </dl>
  </div>

	<div id="tabs-2">
    <dl id = "about_site_info" >

      <dt>
        MyCalendarはRuby on railsを使用して開発しました。
      </dt>
      <dd>
        Windows7上で, Ruby 1.9.3, Rails 3.2.14</br>
        RubyとRailsのHPのリンクはFooterにあります。
      </dd>
      <dt>
        jQuery カレンダープラグイン、Fullcalendarを使用しています
      </dt>
      <dd style = "display: none;">
        fullecalendarを使うとカレンダーを使ったUI画面を簡単に作ることができるだけでなく、
        提供されているオプションを使うことで自分独自のデザインやカスタマイズを行えます。<br/>
        リンクはこちら<a href = "http://arshaw.com/fullcalendar/" class = 'popup'>http://arshaw.com/fullcalendar/</a>
      </dd>

      <dt>
        CSSフレームワークのTwitter Bootstrapを使用しています
      </dt>
      <dd style = "display: none;">
        Bootstrapでモダンなデザインのサイトを作ることができます。<br/>
        リンクはこちら<a href = "http://getbootstrap.com/" class = 'popup'>http://getbootstrap.com/</a>
      </dd>

    </dl>
  </div>

	<div id="tabs-3">
    <dl id = "about_site_info" >

      <dt>
        このサイトのソースコードがgithub.comで参照、ダウンロードできます
      </dt>
      <dd style = "display: none;">
        リンクはこちら<a href = "https://github.com/jimakoji/mycalendar" class = 'popup'>https://github.com/jimakoji/mycalendar</a>
      </dd>

      <dt>
        サーバーはRuby on RailsのPaaS「Heroku」を使っています。
      </dt>
      <dd style = "display: none;">
        HerokuはRuby on Railsを対象とした、Amazon Web Services（AWS）のIaaS上に構築されたPaaSです。
        デプロイには分散リポジトリのGitを利用するなど、Webアプリケーションの開発から公開まで非常に簡単に
        できる優れたプラットフォームです。<br/>
        現在ではRuby以外にもJava、Python、JavaScript（node.js）、Scala、Cloujure、PHP（非公式）などにも対応した
        マルチ言語なプラットフォームになっています。<br/>        
        リンクはこちら<a href = "https://github.com/jimakoji/mycalendar" class = 'popup'>https://github.com/jimakoji/mycalendar</a>
      </dd>

    </dl>
  </div>

</div>

<script type="text/javascript">
  //<![CDATA[
    $(function(){
        $("#about_site_info dt").on("click", function() {
            $(this).next().slideToggle();
        });
        $( "#tabs" ).tabs({ 
          fx: { opacity: 'toggle', duration: 'normal'  }
        });
        $(".popup").click(function(){
          window.open(this.href,"WindowName","width=600,height=500,resizable=yes,scrollbars=yes");
          return false;
	      });
    });
  //]]>
</script>

app/views/static_pages/_contact.html.erb
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">E_mail</a></li>
	</ul>

  <div id="tabs-1">
    <dl id = "contact_site_info" >

      <dt>
        g_mail: 
      </dt>
      <dd style = "display: none;">
        <a href = "mailto:jima0537@gmail.com" >jima0537@gmail.com</a>
      </dd>
      <dt>
        yahoo:
      </dt>
      <dd style = "display: none;">
        <a href = "mailto:jima0537@yahoo.co.jp" >jima0537@yahoo.co.jp</a>
      </dd>

    </dl>
  </div>

</div>

<script type="text/javascript">
  //<![CDATA[
    $(function(){
        $("#contact_site_info dt").on("click", function() {
            $(this).next().slideToggle();
        });
        $( "#tabs" ).tabs({ 
          fx: { opacity: 'toggle', duration: 'normal'  }
        });
    });
 //]]>
</script>

app/views/static_pages/_help.html.erb
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">画面操作･･･etc</a></li>
		<li><a href="#tabs-2">新規作成･･･</a></li>
		<li><a href="#tabs-3">登録について･･･</a></li>
		<li><a href="#tabs-4">データ保存期限について･･･その他</a></li>
	</ul>
	<div id="tabs-1">

    <dl class = "help_site_info" >

      <dt>
        もし画面表示が･･･
      </dt>
      <dd>
        おかしくなったら、F5キーを押すか、ヘッダーにある’Home / ホーム’
        をクリックして、ページリロードしてみてください。
      </dd>

      <dt>
        ３つのカレンダー画面
      </dt>
      <dd style = "display: none;">
        月単位、週単位、日単位でカレンダー表示を切り替えることが出来ます。<br/>
        デフォルトは月単位です。
      </dd>

      <dt>
        週と日単位の表示時間
      </dt>
      <dd style = "display: none;">
        週と日単位の表示時間は6時～22時までです。それ以外の時間帯のスケジュールも作成可能ですが、
        週と日単位のカレンダーには表示されません。月単位のカレンダーには表示されます。皆さん、
        終電があるうちにお家に帰りましょう!!
      </dd>

      <dt>
        投稿コメント
      </dt>
      <dd style = "display: none;">
        右サイドバーにある’Post / 投稿する’をクリックすると投稿コメントできます。表示は直近の
        8件です。皆さんのご意見、インフォメーションお待ちしています。ちなみに投稿コメント欄は
        ログインされていない方にも表示されます。将来的には相手を選んで投稿できるオプションも
        実装したいと考えています。
      </dd>

      <dt>
        ３つのDisplay Mode
      </dt>
      <dd style = "display: none;">
        自分のスケジュールのみ、公開スケジュールのみ、両方、この３つの選択が出来ます。
        ヘッダーの’Display / 表示’をクリックしてみてください。
      </dd>

    </dl>

  </div>
	<div id="tabs-2">

    <dl class = "help_site_info" >

      <dt>
        新規作成･･･
      </dt>
      <dd>
        左上の’新規作成’ボタンをクリックするか、カレンダー上をクリックしてドラッグしてください。
        新規作成の Dialog Window が開きます。
      </dd>

      <dt>
        編集･削除･･･
      </dt>
      <dd style = "display: none;">
        カレンダー上のスケジュールをクリックしてください。Dialog Window が開き、編集か、削除を
        選択できます。
      </dd>

      <dt>
        スケジュールを公開するには･･･
      </dt>
      <dd style = "display: none;">
        スケジュール新規作成か編集のDialog Window を開き、'スケジュールを公開する？’のチェックを
        入れてください。ログインした方全てが閲覧できる状態になります。<br/>
        もちろん、編集で取り消すことも出来ます。<br/>ちなみにインデックスカラーはグリーンに統一されます。
      </dd>

    </dl>

  </div>

	<div id="tabs-3">

    <dl class = "help_site_info" >

      <dt>
        ユーザー登録すると･･･
      </dt>
      <dd>
        そのままログインの状態になり当サイトをご利用できます。意図的にログアウト
        しない限り、次回訪問時もログインした状態でご利用できます。
      </dd>

      <dt>
        名前とE_mailについて･･･
      </dt>
      <dd style = "display: none;">
        名前は本名である必要はありません。お好きなハンドルネームを使ってください。
        E_mailも現状では、E_mailの体裁を整えていれば、登録できてしまいますが、
        今後、パスワードを忘れた際の自動メール配信(パスワード更新ページのお知らせ)を
        予定しているので、実際に使用しているメールアドレスで登録をお願いします。
      </dd>

      <dt>
        パスワードを忘れたら･･･
      </dt>
      <dd style = "display: none;">
        E_mailでご連絡ください。対処します。具体的には管理人がユーザー登録を解除(削除)して,
        新規に再登録してもらうことになります。その際、今までのスケジュールと投稿コメントは消去されます。
        将来的にはパスワード更新ページのリンクをE_mailで自動配信する予定です。
      </dd>

      <dt>
        ユーザー登録を解除するには･･･
      </dt>
      <dd style = "display: none;">
        ユーザー一覧から自分の名前の横にある’削除’ボタンをクリックしてください。ユーザー登録を
        解除しますと、登録されたスケジュールと投稿コメントもすべて消去されます。
      </dd>

      <dt>
        プロフィール変更について･･･
      </dt>
      <dd style = "display: none;">
        ヘッダーの’アカウント’から’ユーザー情報更新’をクリックしてください。
        セキュリティ保持のためからも、パスワードの定期的な変更をお薦めします。
      </dd>
    </dl>

  </div>

	<div id="tabs-4">

    <dl class = "help_site_info" >

      <dt>
        データ保存は約3ヶ月･･･
      </dt>
      <dd>
        3ヶ月以上前のスケジュールデータと投稿コメントは消去します。現在消去作業は手動で行っているため、
        多少誤差がでます。3ヶ月以内のデータが消去されることはありません。将来的には自動化する予定。
      </dd>

      <dt>
        プロフィール画像について･･･
      </dt>
      <dd style = "display: none;">
        当サイトでは、プロフィール写真の管理に’Gravatar’を使用しています。<br/>
        Gravatar (グラバター)はWordPress社のメールアドレスとプロフィール画像を結びつけるサービスです。
       アカウント作成時やコメント投稿時のメールアドレスから、そのアドレスに対応する画像が
       アバターとして表示されます。とても便利なWebサービスです。<br/>
       使用するにはまず<br/>
       <a href="https://ja.gravatar.com/connect/?source=_signup" class = 'popup'>
       https://ja.gravatar.com/connect/?source=_signup、 ここで無料登録</a>
      </dd>

      <dt>
        利用環境について･･･
      </dt>
      <dd style = "display: none;">
        動作確認したブラウザは下記の通りです。<br/>
        Internet Explorer9<br/>
        Firefox Ver26.0<br/>
        Google Chrome バージョン 32.0.1700.102 m<br/>
        Safari 5.1.7<br/>
        Opera 12.16<br/>
      </dd>
    </dl>

  </div>

</div>

<script type="text/javascript">
  //<![CDATA[
    $(function(){
      $(".help_site_info dt").on("click", function() {
          $(this).next().slideToggle();
      });
      $( "#tabs" ).tabs({ 
        fx: { opacity: 'toggle', duration: 'normal'  },
        collapsible: true,
      });
      $(".popup").click(function(){
        window.open(this.href,"WindowName","width=600,height=500,resizable=yes,scrollbars=yes");
        return false;
	    });
    });
 //]]>
</script>

app/views/static_pages/_home.html.erb
<div id = 'home', class = "center hero-unit">

  <h2>Welcome to the MyCalendar</h2>

  <%= link_to "Sign in / ログイン", signin_path, id: 'log_in_btn', class: "btn btn-large btn-primary", :method => :get, :remote => true %>
  <%= link_to "Sign up now! / ユーザー登録", signup_path, class: "btn btn-large btn-primary", :method => :get, :remote => true %>
</div>

app/views/static_pages/_roadmap.html.erb
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">改善すべき点</a></li>
		<li><a href="#tabs-2">追加機能の予定</a></li>
		<li><a href="#tabs-3">その他･･･etc</a></li>
	</ul>
  <div id="tabs-1">
    <dl class = "roadmap_site_info" >

      <dt>
        Dialog Windowについて
      </dt>
      <dd>
        Dialog Windowをオープンすると画面下部に無駄な余白ができる。
        その余白を消したい。（原因がよくわからない･･･）
      </dd>

      <dt>
        コードをリファクタリングする。
      </dt>
      <dd style = "display: none;">
        思いつきでプログラミングしている部分が多々あり、コードの記述が冗長な部分が多い。
        整理したい。
      </dd>

    </dl>
  </div>

	<div id="tabs-2">
    <dl class = "roadmap_site_info" >

      <dt>
        認証機構について: 
      </dt>
      <dd>
        認証機構を'devise'Pluginに差し替え、自動メール配信を可能にする。
        メールサーバーはGmailかSendGridを利用する予定
      </dd>

      <dt>
        ファイルアップロードについて： 
      </dt>
      <dd style = "display: none;">
        ファイルアップロード機能を実装。外部ストレージを使う予定（たとえば'DropBox'）<br/>
        無理ならデータベースに保存。
        必要性は感じないが、1時的なファイル置き場として使用できるようにしたい。
      </dd>

      <dt>
        ゲーム機能･･･？
      </dt>
      <dd style = "display: none;">
        暇つぶし用のページを作りたい。<br/>
        例えばゲーム、midiフレーズをgenerateするページ等々
      </dd>

    </dl>
  </div>

	<div id="tabs-3">
    <dl class = "roadmap_site_info" >

      <dt>
        参考にしたサイト
      </dt>
      <dd>
        Ruby on Rails チュートリアル<a href = "http://railstutorial.jp/" class = 'popup'>http://railstutorial.jp/</a>
        <br/>
        初歩的なことから、高度な内容までわかりやすく解説されています。<br/>
        Michael Hartl さん、ありがとう。
      </dd>

    </dl>
  </div>
</div>



<script type="text/javascript">
  //<![CDATA[
    $(function(){
        $(".roadmap_site_info dt").on("click", function() {
            $(this).next().slideToggle();
        });
        $( "#tabs" ).tabs({ 
          fx: { opacity: 'toggle', duration: 'normal'  }
        });
        $(".popup").click(function(){
          window.open(this.href,"WindowName","width=600,height=500,resizable=yes,scrollbars=yes");
          return false;
	      });
    });
 //]]>
</script>

app/views/static_pages/site_info.js.erb
<% 
  case @flag
    when 'help'
      site_info = 'help'
      title = 'HELP / 使い方'
    when 'about'
      site_info = 'about'
      title = 'ABOUT / このサイトについて'
    when 'contact'
      site_info = 'contact'
      title = 'CONTACT / 連絡先 E_mail'
    when 'roadmap'
      site_info = 'roadmap'
      title = 'ROADMAP / 今後の課題'
  end
%>

$('#site_info').html( "<%= escape_javascript(render site_info ) %>" );
$('#site_info_dialog').dialog({
        title: '<%= title %>',
        modal: false,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 700,
        close: function(event, ui) {
                                     $('#site_info_dialog').dialog('destroy');
                                     $('#site_info').empty();
                                    }
});