config/routes.rb
FullcalendarMasterRails3::Application.routes.draw do

  resources :attachments do
    get "serve", :on => :member
  end

  get "download_file" => "attachments#download_file", as: 'download_file'

  resources :information

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]

  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' 
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/roadmap', to: 'static_pages#roadmap'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'events#index'

  post  'events/demo_create' => 'events#demo_create'

  get   'events/db_cleanup'    => 'events#db_cleanup', :as => 'db_cleanup'
  get   'events/get_events' => 'events#get_events', :as => 'get_events'
  post  'events/resize'     => 'events#resize'
  post  'events/move'       => 'events#move'

  resources :events

end

app/models/information.rb
# == Schema Information
#
# Table name: information
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Information < ActiveRecord::Base
  attr_accessible :description, :title

  validates :title,  presence: true, length: { maximum: 50 }
  validates :description,  presence: true, length: { maximum: 140 }

  default_scope order: 'information.created_at DESC'

end

app/controllers/information_controller.rb
# coding: utf-8
class InformationController < ApplicationController

  before_filter :admin_user_for_information, except: :index

  def index

  end

  def show
    @information = Information.find(params[:id])
  end

  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
    @information = Information.find(params[:id])
  end

  def create
    @information = Information.new(params[:information])
      if @information.save
        flash[:success] = "Information created! / お知らせ新規作成完了!"
        render 'close_admin_info_dialog'
      else
        render 'new'
      end

  end

  # PUT /information/1
  # PUT /information/1.json
  def update
    @information = Information.find(params[:id])
      if @information.update_attributes(params[:information])
        flash[:success] = "Information updated! / お知らせ更新完了!"
        render 'close_admin_info_dialog'
      else
        render 'edit'
      end
  end

  def destroy
    @information = Information.find(params[:id])
    @information.destroy
    flash[:success] = "Information removed! / お知らせ削除完了"
    redirect_to root_path
  end

  private

    def admin_user_for_information
      if signed_in?
        unless current_user.admin?
          flash[:error] = "You Can't / 管理者以外、お知らせの作成、編集、削除はできません"
          redirect_to root_path
        end
      else
        flash[:error] = "You Can't / 管理者以外、お知らせの作成、編集、削はできません"
        redirect_to root_path 
      end
    end

end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_edit.html.erb
<%= render 'edit_form' %>

<br/>

<%= button_to 'Show', @information, method: :get, remote: true %> 

app/views/information/_edit_form.html.erb
<%= form_for @information, :url => { :action => 'update' },remote: true do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description, :rows => 4, :cols => 30  %>

  <br/>
  <br/>

    <%= f.submit %>

<% end %>

app/views/information/_index.html.erb
<h4>お知らせ</h4>

<dl>

<% if signed_in? %>
  <% if current_user.admin? %>
    <% remote_value = true %>
  <% end %>
<% else %>
  <% remote_value = false %>
<% end %>

<% @information.each do |information| %>
    <% time = information.created_at.strftime(" (%-m / %-d)") %>
    <dt><%= information.title + "　" + time %></dt>
    <dd style = "display: none;"><%= simple_format information.description %>
    <% if signed_in? %>
      <% if current_user.admin? %>
        <p><span><%= link_to 'Show', information, remote: remote_value %></span>
        <span><%= link_to 'Edit', edit_information_path(information), remote: remote_value %></span>
        <span><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure? / 削除します' } %></span>
        </p>
      <% end %>
    <% end %>

    </dd>

<% end %>
</dl>

<% if signed_in? %>
  <% if current_user.admin? %>
    <%= button_to 'New Information', new_information_path, method: :get, remote: remote_value %>
  <% end %>
<% end %>

app/views/information/_new.html.erb
<%= render 'new_form' %>

app/views/information/_new_form.html.erb
<%= form_for @information, :url => { :action => 'create' }, remote: true do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 4, :cols => 30  %>
  </div>

  <br/>

    <%= f.submit "お知らせ新規作成" %>

<% end %>

app/views/information/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Title:
  <%= @information.title %>
</p>

<p>
  Description:
  <%= @information.description %>
</p>

<br/>

<%= button_to 'Edit', edit_information_path(@information), method: :get, remote: true %>

app/views/information/close_admin_info_dialog.js.erb
$('#admin_info_dialog').dialog('destroy');
admin_info_dialog_reset();

<%= render 'shared/flash_message' %>
location.reload();

app/views/information/edit.js.erb
$('#admin_info').html( "<%= escape_javascript(render 'edit') %>" ); 
$('#admin_info_dialog').dialog({
        title: 'Edit Information / お知らせ編集',
        modal: true,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 500,

        close: function(event, ui) { 
                 $('#event_dialog').dialog('destroy');
                 admin_info_dialog_reset();
               }
});

app/views/information/new.js.erb
$('#admin_info').html( "<%= escape_javascript(render 'new') %>" ); 
$('#admin_info_dialog').dialog({
        title: 'New Information / お知らせ作成',
        modal: true,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 500,

        close: function(event, ui) { 
                 $('#admin_info_dialog').dialog('destroy');
                 admin_info_dialog_reset();
               }
});

app/views/information/show.js.erb
$('#admin_info').html( "<%= escape_javascript(render 'show') %>" ); 
$('#admin_info_dialog').dialog({
        title: 'New Information / お知らせ作成',
        modal: true,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 660,

        close: function(event, ui) { 
                 $('#event_dialog').dialog('destroy');
                 admin_info_dialog_reset();
               }
});