config/routes.rb
FullcalendarMasterRails3::Application.routes.draw do

  resources :attachments do
    get "serve", :on => :member
  end

  get "download_file" => "attachments#download_file", as: 'download_file'

  resources :information

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]

  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' 
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/roadmap', to: 'static_pages#roadmap'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'events#index'

  post  'events/demo_create' => 'events#demo_create'

  get   'events/db_cleanup'    => 'events#db_cleanup', :as => 'db_cleanup'
  get   'events/get_events' => 'events#get_events', :as => 'get_events'
  post  'events/resize'     => 'events#resize'
  post  'events/move'       => 'events#move'

  resources :events

end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id           :integer          not null, primary key
#  file_content :binary(2097152)
#  file_name    :string(255)
#  mime_type    :string(255)
#  file_size    :integer
#  event_id     :integer
#  public       :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Attachment < ActiveRecord::Base
  attr_accessible :file_content, :file_name, :mime_type, :file_size, :public

  belongs_to :event

#  validates :event_id, presence: true

#  def self.cleanup
#    Attachment.delete_all(["created_at < ?", 3.months.ago])
#  end

end

app/controllers/attachments_controller.rb
# coding: utf-8
class AttachmentsController < ApplicationController
  def index
  end

  def show
    @attachment = Attachment.find(params[:id])
    @viewer_grid = params[:viewer_grid]
  end

  def serve
    @attachment = Attachment.find(params[:id])
    send_data(@attachment.file_content, 
              :type => @attachment.mime_type,
              :filename => "#{@attachment.file_name}",
              :disposition => 'inline'
              )
  end

  def download_file
    @attachment = Attachment.find(params[:id])
    send_data(@attachment.file_content, 
              :type => @attachment.mime_type,
              :filename => "#{@attachment.file_name}",
              :disposition => "attachment"
              )
  end

  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    flash[:success] = "Attachment removed! / 添付ファイル削除完了"
    render 'reload_event_edit_page'
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/reload_event_edit_page.js.erb
$('#reload_event_edit_page_button').click();

$('#attachment_info').removeClass();

var flash_fadeout_timer;
var remove_class_empty_timer;
clearTimeout(flash_fadeout_timer);
clearTimeout(remove_class_empty_timer);

<% flash.each do |key, value| %>
  $('#attachment_info').addClass('<%= "alert alert-#{key}" %>').html('<%= value %>' );
<% end %>

$('#attachment_info').fadeIn("fast");

flash_fadeout_timer = setTimeout( function(){
                                    $('#attachment_info').fadeOut("slow");
                                  }, '5000');
remove_class_empty_timer = setTimeout( function(){
                                         $('#attachment_info').removeClass().empty();
                                       }, '6000');

app/views/attachments/show.js.erb
$('#viewer_<%= @viewer_grid %>').html('<%= image_tag serve_attachment_path(@attachment) %>');