config/routes.rb
FullcalendarMasterRails3::Application.routes.draw do

  resources :attachments do
    get "serve", :on => :member
  end

  get "download_file" => "attachments#download_file", as: 'download_file'

  resources :information

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]

  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' 
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/roadmap', to: 'static_pages#roadmap'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'events#index'

  post  'events/demo_create' => 'events#demo_create'

  get   'events/db_cleanup'    => 'events#db_cleanup', :as => 'db_cleanup'
  get   'events/get_events' => 'events#get_events', :as => 'get_events'
  post  'events/resize'     => 'events#resize'
  post  'events/move'       => 'events#move'

  resources :events

end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  default_scope order: 'microposts.created_at DESC'

  def self.cleanup
    Micropost.delete_all(["created_at < ?", 3.months.ago])
  end

end

app/controllers/microposts_controller.rb
# coding: utf-8
class MicropostsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :destroy]
  before_filter :correct_user,   only: :destroy

  def index
    
  end

  def new
    @micropost = current_user.microposts.build
  end

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Posted! / 投稿完了!"
      render 'close_micropost_dialog'
    else
      render 'new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Your post destroyed! / 投稿コメント削除完了!"
    redirect_to root_url
  end

  private

    def correct_user
#      @micropost = current_user.microposts.find_by_id(params[:id])
      @micropost = Micropost.find_by_id(params[:id])
      if @micropost.user_id != current_user.id and !current_user.admin?
        flash[:error] = "自分以外の投稿コメントは削除できません"
        redirect_to root_url
      end 
    end

end

app/views/microposts/_edit.html.erb
<%= render 'edit_form' %>

<br/>

<%= button_to 'Show', @information, method: :get, remote: true %> 

app/views/microposts/_edit_form.html.erb
<%= form_for @information, :url => { :action => 'update' },remote: true do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description, :rows => 4, :cols => 30  %>

  <br/>
  <br/>

    <%= f.submit %>

<% end %>

app/views/microposts/_index.html.erb
<h4>投稿コメント</h4>

<dl>
  <% i = 0; display = "display: ;" %>
  <% @microposts.each do |micropost| %>
    <% display = "display: none;" if i > 2 %>
    <% time = micropost.created_at.strftime(" (%-m / %-d)") %>
    <dt style = 'clear: both;'><%= User.find_by_id(micropost.user_id).name + "さん　" + time %></dt>
    <dd style = '<%= display %>' ><%= simple_format(micropost.content) %>
    <% if signed_in? %>
      <% if current_user.id == micropost.user_id  or current_user.admin? %>
        <p>
          <span id = 'destroy_link'><%= link_to '削除', micropost, method: :delete, data: { confirm: 'Are you sure? / 削除します' } %></span>
        </p>
      <% end %>
    <% end %>
    </dd>
    <% i += 1 %>
  <% end %>

</dl>

<% if signed_in? %>
    <%= button_to 'Post / 投稿する', new_micropost_path, method: :get, remote: true %>
<% end %>

app/views/microposts/_new.html.erb
<%= render 'new_form' %>

app/views/microposts/_new_form.html.erb
<%= form_for @micropost, :url => { :action => 'create' }, remote: true do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content, :rows => 4, :cols => 30  %>
  </div>

  <br/>

    <%= f.submit %>

<% end %>

app/views/microposts/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Title:
  <%= @information.title %>
</p>

<p>
  Description:
  <%= @information.description %>
</p>

<br/>

<%= button_to 'Edit', edit_information_path(@information), method: :get, remote: true %>

app/views/microposts/close_micropost_dialog.js.erb
$('#micropost_dialog').dialog('destroy');
micropost_dialog_reset();

<%= render 'shared/flash_message' %>
location.reload();

app/views/microposts/edit.js.erb
$('#admin_info').html( "<%= escape_javascript(render 'edit') %>" ); 
$('#admin_info_dialog').dialog({
        title: 'Edit Information / お知らせ編集',
        modal: true,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 500,

        close: function(event, ui) { 
                 $('#event_dialog').dialog('destroy');
                 admin_info_dialog_reset();
               }
});

app/views/microposts/new.js.erb
$('#micropost').html( "<%= escape_javascript(render 'new') %>" ); 
$('#micropost_dialog').dialog({
        title: 'New Post / 投稿コメント作成',
        modal: true,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 500,

        close: function(event, ui) { 
                 $('#micropost_dialog').dialog('destroy');
                 micropost_dialog_reset();
               }
});

app/views/microposts/show.js.erb
$('#admin_info').html( "<%= escape_javascript(render 'show') %>" ); 
$('#admin_info_dialog').dialog({
        title: 'New Information / お知らせ作成',
        modal: true,
        position: {
                 of: '.fc-header',
                 my: "center top",
                 at: "center bottom"
                },
        width: 660,

        close: function(event, ui) { 
                 $('#event_dialog').dialog('destroy');
                 admin_info_dialog_reset();
               }
});